### ISSUE TITLE
Potentially missing header fields cause errors

### ISSUE THREAD

**Issue by jfrank14** [andrewdavey/postal#80] opened 2014-08-22 21:57 UTC
I posted about this on StackOverflow (http://stackoverflow.com/questions/25455356/send-fails-if-there-are-no-recipients) but I'll write it up here as well.

I'm trying to use Postal to send templated emails, and it works very well, except for the way it handles missing recipients.

My main template looks like this:

```
@Modeltype MyModel
To: @Html.Raw(Model.To.ToHeaderString)
Cc: @Html.Raw(Model.Cc.ToHeaderString)
Subject: MySubject
Views: Text, Html
```

And my model has To and Cc collections. But the problem is that if, say, the Cc collection is empty, the email fails with this error:

```
The parameter 'addresses' cannot be an empty string.
```

(If I emit the full Cc header ONLY IF the collection is non-empty, and it is, then this creates a blank line in the template, and this causes a different error--it sends a message that's just the template, un-parsed.)

But I don't know at design time if there will be CC recipients, and so there's no way to use the template. For now, I work around this by getting a MailMessage, manually setting the recipients, and sending that, but it's pretty kludgy.

More generally, I suspect that any blank header will cause problems, but you might not know until runtime if a given header should have a value.

**Comment by andrewdavey** [comment] 2014-08-25 15:20
Duplicate of #38

**Closed as completed by andrewdavey** 2014-08-25 15:20 UTC
